# .github/funding.yml

custom: [
  "Monero: 4A2hj1kK5nXUzmVEBVZyEb2Y3oL4KLBG39zREcjXYZh5Ji8hia2na6xF7836tw1zdGUnKr3ZMDYt68NU1ydVpHhrT9AEywB",
  "Bitcoin: bc1q5304udm5pwgemd70wgklqk8nm44lxkkguzd65v",
  "Zcash: t1LbQShCfcdXMCkN1AkzwvF15P98s8xjtcV",
  "USDC Solana: GW6csdpnkb7v5DiFkiVRS2edEQWfsd1oxhyPztdzgaip"
]